### PR TITLE
Update AMD Microcode to 2024-11-21 drop

### PR DESCRIPTION
**Pull request by bleader**
Update for families 17h and 19h from upstream.

### CODE REVIEW

**Comment by bleader** [comment]
Scratch Build: http://koji.xcp-ng.org/taskinfo?taskID=71467

**Review by stormi — APPROVED** [review]
LGTM. Make sure you check the updated bins are indeed present in the built RPM.

**Review by gduperrey — APPROVED** [review]

**Comment by bleader** [comment]
I did verify the bins are the right one.

**Comment by bleader** [comment]
Koji Build (v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=71514

**Pull request merged**
